global:
  scrape_interval: 5s
  evaluation_interval: 5s 

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "litestar"
    metrics_path: /metrics
    static_configs:
      - targets: ["backend:8080"]
        labels:
          app: "litestar"